# Generated by Django 4.0.3 on 2022-04-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0002_email_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='date_joined',
            new_name='created_at',
        ),
    ]
