# Generated by Django 4.0.3 on 2022-04-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0005_alter_label_email_alter_label_title_alter_label_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-id']},
        ),
    ]
