# Generated by Django 4.0.3 on 2022-04-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0006_alter_label_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id']},
        ),
    ]
