# Generated by Django 4.0.3 on 2022-04-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0012_email_archive_alter_forward_to_alter_label_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='show',
            field=models.CharField(default='Y', max_length=10),
        ),
    ]
