# Generated by Django 4.0.3 on 2022-04-05 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0013_email_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='delete',
            field=models.CharField(default='N', max_length=10),
        ),
        migrations.AddField(
            model_name='email',
            name='trash',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
