# Generated by Django 4.0.3 on 2022-04-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0014_email_delete_email_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='trash',
            field=models.DateTimeField(null=True),
        ),
    ]
