# Generated by Django 4.0.3 on 2022-04-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0015_alter_email_trash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='delete',
            new_name='deleted',
        ),
    ]
