# Generated by Django 4.0.3 on 2022-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0016_rename_delete_email_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
