# Generated by Django 4.0.3 on 2022-03-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audience',
        ),
    ]
